### ISSUE TITLE
 Super expression must either be null or a function, not undefined 

### ISSUE THREAD

**Issue by mohirbeck** [xeger/quill-image#18]
Everything works fine on dev (npm run dev) but after the build, I have this error:

Super expression must either be null or a function, not undefined.

Without the BlotFormatter module, it also works fine.

I'm using nuxt.js and quill.js

![image](https://user-images.githubusercontent.com/60925005/218714142-90152b52-7f03-4566-84cd-999174829c18.png)

**Comment by xeger** [comment]
This package is intended as a replacement for `quill-blot-formatter` (and for its fork, `quill-image-actions`) so it's possible there is some incompatibility. I've never tested them together. They all hook into the same parts of Quill and might conflict with one another.

`Super expression must be null or a function` sounds to me like this module, or maybe BlotFormatter, is trying to extend a built-in format. The obvious culprit is `Image` since I know 100% that my module extends the built-in Quill `image`. I believe BlotFormatter also does, but it does that in a less extensible way (it _replaces_ Image whereas I dynamically extend `image`).

Do you have a stack trace available? Even obfuscated/minimized is fine; I might learn something from it.

Are you registering the `Image` format when you configure your Quill instance?
