### ISSUE TITLE
`quill-image-actions@0.7.1` won't work with `quill@2.0.0-dev.4` ?

### ISSUE THREAD

**Issue by anburocky3** [xeger/quill-image#21]
Our project needs to have tabular column, but sadly quill stable version doesn't have tabular column. In order to use `quill-better-table`, we need to use `quill@2.x`. 

When using like that, the above package is not working as expected.

![image](https://user-images.githubusercontent.com/15264938/231456081-484df6ec-2d99-410f-91ed-8912d7aa0cf1.png)

**Comment by xeger** [comment]
Quill is [semantically versioned](https://semver.org/); the "v2" means that the interface is not compatible with Quill v1. I would need to rewrite my modules for proper Quill v2 support. I am using Quill v1 with my products because it is stable, and unfortunately I don't have time to research v2.

I created a [v2 branch](https://github.com/xeger/quill-image/compare/v2) in this repo to see how badly things were broken. As expected, they are pretty broken; my module does not initialize.

You're welcome to try a rewrite if you'd like. You may want to just stick with Quill 1 unless Quill 2 offers something you really need.

**Comment by anburocky3** [comment]
I still want the Quill stable version, but it doesn't support tabular columns. Is there any way, to have tabular columns in v1?

**Comment by xeger** [comment]
Sorry, I don't know. I don't think v1 does tables or tabular columns at all. There may be some module that tries to do that.

Could you build support for tabular columns "outside" of the editor, as part of your app?
i.e. your app could instantiate one editor per column, and you could have some UI to add/remove columns.

**Comment by anburocky3** [comment]
Looks like big work to me. Thanks for your reply. Since its out of scope of this package, will close this issue. Thank you.
