### ISSUE TITLE
usage examples of ImageActions properties

### ISSUE THREAD

**Issue by mkamalkayani** [xeger/quill-image#6]
Is there any usage examples to pass ImageActions properties? 

I want to get the image width. I think I can get the width from the img node which I can obtain by `getTargetElement()` but don't know how to get the img node.

**Comment by xeger** [comment]
The normal way to use Quill is to let the user edit things however he wants, and then subscribe to [text-change](https://quilljs.com/docs/api/#text-change) events. Whenever the user edits the document, Quill will fire an event and you can call `getContents()` on the editor to return the JSON representation of the rich text (as a Quill delta). The JSON objects will include one that represents your image and it will have a `width` and `height` in its `attributes`.

If you want to use HTML, not JSON, then the idea is similar but you can read the `innerHTML` of the Quill editor element when the `text-change` event fires.

Does that answer your question? I'm not 100% clear on your goal. The img node should be returned by `getTargetElement` whenever the user has selected an image -- but it might be difficult to access `getTargetElement` since it's an implementation detail of the package. It is usually easier to use the Quill editor's API to learn about the document and its images.

**Comment by mkamalkayani** [comment]
What you suggested seems reasonable. I have to try it out.
