### ISSUE TITLE
How can I hide the alignment icons?

### ISSUE THREAD

**Issue by mkamalkayani** [xeger/quill-image#7]
How can I hide the alignment icons?

**Comment by xeger** [comment]
You can disable the alignment actions (including the icons) using inheritance. If you extend `ImageSpec` you can override `getActions` and instead of [returning three actions](https://github.com/xeger/quill-image/blob/main/packages/quill-image-actions/src/specs/BlotSpec.ts#L27) you can just return two.

When you `new Quill`, pass your own, customized spec in the [options](https://github.com/xeger/quill-image/blob/main/packages/quill-image-actions/src/Options.ts#L61).
