### ISSUE TITLE
Can I add a custom icon and handlers in place of alignment icons?

### ISSUE THREAD

**Issue by mkamalkayani** [xeger/quill-image#8]

**Comment by xeger** [comment]
Custom icon is supported. When you initialize Quill, you pass it some options for this module, like so:

```
new Quill({modules: {imageActions: {OPTIONS}}});
```

The options are defined [here](https://github.com/xeger/quill-image/blob/main/packages/quill-image-actions/src/Options.ts#L63). (Unfortunately the Quill typings don't let me specify the type of the `imageActions:` key, so TypeScript will not make any inference... but the `Options` interface does define the options we take.)

`Options.align` is an instance of [AlignOptions](https://github.com/xeger/quill-image/blob/main/packages/quill-image-actions/src/Options.ts#L35) and one of the fields of `AlignOptions` is the set of icons (as SVG markup) for left/center/right. In the [default options](https://github.com/xeger/quill-image/blob/main/packages/quill-image-actions/src/Options.ts#L67) you can find an example for the default SVGs. Just pass different SVG strings inside the OPTIONS object that you provide to `new Quill` and you can customize the icons.

Customizing the handler is also supported, but is much more complex. You can pass custom `specs` as part of OPTIONS. You can see that the [default specs](https://github.com/xeger/quill-image/blob/main/packages/quill-image-actions/src/Options.ts#L68) include `ImageSpec` and `IframeVideoSpec`. The `ImageSpec` class has a `getActions` that defines the [valid actions](https://github.com/xeger/quill-image/blob/81cf7ee12797968a12dae30cb61fe31a5daca448/packages/quill-image-actions/src/specs/BlotSpec.ts#L28) for an image -- each action is a class. And, the `AlignAction` class [instantiates](https://github.com/xeger/quill-image/blob/main/packages/quill-image-actions/src/actions/align/AlignAction.ts) `DefaultAligner`. The `DefaultAligner` is the pcode that actually handles](https://github.com/xeger/quill-image/blob/main/packages/quill-image-actions/src/actions/align/DefaultAligner.ts#L23) the align requests.

Soooo ... if you are _really_ motivated, you can define a `class KamalImageSpec extends ImageSpec` and its `getActions` can return a `KamalAlignAction extends AlignAction` and that action can instantiate a `KamalAligner` that customizes the handlers. But, as you can see, it's very hard to customize because it requires a bunch of inheritance.

Not my favorite design -- but it's how the original package worked, and I don't have enough energy to redesign the package.
